### ISSUE TITLE
Put lightbulb into bathroom

### ISSUE THREAD

**Issue by manpages** [Radivarig/geek-flat-zagreb#10]
How many programmers does it take to replace a lightbulb?

**Comment by manpages** [comment]
I'll be in the city today, will buy some bulbs. How many do we need, @Radivarig?

**Comment by Radivarig** [comment]
None, that's a hardware problem. But `['bathroom', 'kitchen'].length`

**Comment by manpages** [comment]
Didn't manage to get bulbs — woke up too late.

Today will work all day, so no chance I'm getting those today as well :(

**Comment by manpages** [comment]
Bought two bulbs.
